openapi: 3.0.1
info:
  title: API Ecommerce
  description: Documentación de la API Ecommerce, que facilita la gestión de productos.
  version: 1.0.0

paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Productos
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

    post:
      summary: Crea un nuevo producto
      tags:
        - Productos
      requestBody:
        description: Información del nuevo producto
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Producto creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

  /api/products/{pid}:
    get:
      summary: Obtiene un producto por ID
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado

    put:
      summary: Modifica un producto existente
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      requestBody:
        description: Información del producto a actualizar
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Producto actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado

    delete:
      summary: Elimina un producto
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '204':
          description: Producto eliminado exitosamente
        '404':
          description: Producto no encontrado

  /api/products/productscategory:
    get:
      summary: Obtiene productos con su categoría
      tags:
        - Productos
      responses:
        '200':
          description: Lista de productos con categorías
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductWithCategory'

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: ID del producto
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        category:
          type: string
          description: ID de la categoría asociada
        thumbnail:
          type: string
          description: URL de la imagen del producto
        code:
          type: string
          description: Código único del producto
        stock:
          type: integer
          description: Cantidad en stock
        status:
          type: boolean
          description: Estado del producto (activo/inactivo)
      required:
        - title
        - description
        - price
        - category
        - code

    ProductWithCategory:
      type: object
      properties:
        _id:
          type: string
          description: ID del producto
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        category:
          type: string
          description: ID de la categoría asociada
        thumbnail:
          type: string
          description: URL de la imagen del producto
        code:
          type: string
          description: Código único del producto
        stock:
          type: integer
          description: Cantidad en stock
        status:
          type: boolean
          description: Estado del producto (activo/inactivo)
        categoryDetails:
          type: object
          properties:
            _id:
              type: string
              description: ID de la categoría
            name:
              type: string
              description: Nombre de la categoría
      required:
        - title
        - description
        - price
        - category
        - code
